autocmd ColorScheme * highlight ExtraWhitespace ctermbg=red guibg=red

call plug#begin()
let g:ycm_auto_trigger = 0
let g:ycm_add_preview_to_completeopt = 0
let g:ycm_autoclose_preview_window_after_completion = 0
let g:ycm_autoclose_preview_window_after_insertion = 1
let g:ycm_collect_identifiers_from_tags_files = 1
let g:ycm_confirm_extra_conf = 0
let g:ycm_global_ycm_extra_conf = '~/.ycm_extra_conf.py'
"let g:ycm_key_invoke_completion = '<C-e>'
let g:ycm_key_list_previous_completion=['<C-p>']
let g:ycm_key_list_select_completion = ['<C-n>']
let g:ycm_register_as_syntastic_checker = 1
let g:ycm_show_diagnostics_ui = 0
let g:ycm_enable_diagnostic_signs = 0
let g:ycm_server_log_level = 'error'
let g:ycm_use_ultisnips_completer = 1
let g:ycm_filetype_blacklist = {
      \ 'markdown' : 1,
      \ 'notes' : 1,
      \ 'tex' : 1,
      \ 'text' : 1,
      \ 'unite' : 1,
      \ 'vim' : 1,
      \ 'nim' : 1,
      \ 'sql' : 1,
\}
" \ 'typescript' : 1,
" \ 'javascript' : 1,
let g:ycm_semantic_triggers = {
      \ 'gitcommit' : ['#'],
      \ 'clojure' : ['(', '/'],
      \ 'nim' : ['.'],
      \ 'typescript' : ['.']
      \ }
nnoremap <space>h :YcmCompleter GetType<cr>
nnoremap gt :YcmCompleter GoTo<cr>
nnoremap gd :YcmCompleter GoToDefinition<cr>
nnoremap <c-]> :YcmCompleter GoToDefinition<cr>
" nnoremap <leader>jd :YcmCompleter GoToDefinitionElseDeclaration<cr>
"Plug 'Valloric/YouCompleteMe', { 'do': 'cd ~/configs/dotvim/plugged/YouCompleteMe && git submodule update --init --recursive && python2 install.py' }

let g:ale_enabled=1
let g:ale_sign_error = '#'
let g:ale_sign_warning = '?'
let g:ale_lint_on_text_changed = 'normal'
let g:ale_lint_on_insert_leave = 1
let g:ale_sign_column_always = 1
let g:ale_lint_delay = 500
let g:ale_set_quickfix = 1
let g:airline#extensions#ale#enabled = 1
Plug 'w0rp/ale'

Plug 'jwhitley/vim-matchit'
Plug 'majutsushi/tagbar'
Plug 'mbbill/undotree'
Plug 'scrooloose/nerdtree'
Plug 'vim-scripts/L9'

let g:UltiSnipsSnippetsDir = "~/configs/dotvim/snippets"
Plug 'SirVer/ultisnips'
call plug#end()

if has("gui_running")
	"set background=dark
	"colors peaksea
	"let moria_fontface = 'mixed'
	"let moria_monochrome = 1
	set guioptions-=T " No toolbar
	set guioptions-=m " No menubar
	set gfn=Hack\ Regular\ 10
	set cursorline
	set ttyfast
	set guicursor=a:blinkon0
endif


" Sanity check for colors
if $TERM == "xterm-256color" || $TERM == "screen-256color" || $COLORTERM == "gnome-terminal"
	set t_Co=256
endif

" System
colors peaksea
set background=dark

set nocompatible
set listchars=tab:>-,eol:$,trail:.,extends:#
set backspace=indent,eol,start
set tm=500 " time out to 500msec
set history=50
set wildignore=*.swp,*.bak,*.pyc,*.class,*.o

"set textwidth=78
"set softtabstop=4
"set shiftwidth=4
"set tabstop=4

" Put quickfix window always on bottom
botright cwindow
nnoremap Q gqap
vnoremap Q gq

" Visual
set statusline=[%n]\ %<%.99f\ %h%w%m%r%y%{exists('g:loaded_fugitive')?fugitive#statusline():''}%{exists('g:loaded_rvm')?rvm#statusline():''}%=%-16(\ %l\[%v\],%c\ %)%P
syntax on

" Automatically open and close the popup menu / preview window
au CursorMovedI,InsertLeave * if pumvisible() == 0|silent! pclose|endif
set completeopt=menuone,menu,longest,preview

set nowrap
set nobackup
set noswapfile
"set list
set ruler
set laststatus=2
set hlsearch
set number
set wildmenu
set showtabline=2

" Display incomplete commands
set showcmd

" Do incremental searching
set incsearch

" When splitting, don't substitute the current
" buffer with the newly opened one
set splitbelow
set splitright
" All splits are equal
autocmd VimResized * wincmd =
set fillchars+=vert:│

" Sane indent
set autoindent
set smarttab
set smartindent
set copyindent

" Padding when scrolling
" Vertical
set scrolloff=5
" Horizontal
set sidescrolloff=80

filetype on
filetype plugin indent on
"set autoindent

" In many terminal emulators the mouse works just fine, thus enable it.
if has('mouse')
    set mouse=a
endif

" #######################
" Encoding section
" #######################
" Default file encoding for new files
setglobal fenc=utf-8
"
" Auto detect file encoding when opening a file. To check what file encoding was
" selected run ":set fenc" and if you know the auto detection failed and want to
" force another one run ":edit ++enc=<your_enc>".
set fencs=utf-8,latin-1

" Internal encoding used by vim buffers, help and commands
set encoding=utf-8

" Terminal encoding used for input and terminal display
" Make sure your terminal is configured with the same encoding.
set tenc=utf-8

" in human-language files, automatically format everything at 72 chars:
autocmd FileType mail,human set formatoptions+=t textwidth=72
" for C-like programming, have automatic indentation:
autocmd FileType c,cpp,slang set cindent
" for actual C (not C++) programming where comments have explicit end
" characters, if starting a new line in the middle of a comment automatically
" insert the comment leader characters:
autocmd FileType c set formatoptions+=ro

" Reveal extra white spaces
"highlight ExtraWhitespace ctermbg=red guibg=red
" Show trailing whitespace:
match ExtraWhitespace /\s\+$/
" Show trailing whitepace and spaces before a tab:
match ExtraWhitespace /\s\+$\| \+\ze\t/
" Alternatively, the following pattern will match trailing whitespace, except
" when typing at the end of a line.
"match ExtraWhitespace /\s\+\%#\@<!$/

"#################################
"########### Mappings ############
"#################################
let mapleader = ";"

" Split current buffer
nnoremap <leader>w <C-w>v<C-w>l

" Reload vimrc
nnoremap <leader><leader>v :source $MYVIMRC<CR>

" Open quickfix window
nnoremap <leader>c :bot copen<CR>

" Mappings for VimDiff
if &diff
	nnoremap <leader>1 diffput
	nnoremap <leader>2 diffget
endif

" Ctrl-C behaves like pressing Esc
inoremap <C-c> <Esc>

" Allow vi moving in insert mode when Alt is pressed
inoremap <A-h> <Left>
inoremap <A-k> <Up>
inoremap <A-j> <Down>
inoremap <A-l> <Right>
" Scrolling
nnoremap <C-A-j> <PageDown>
nnoremap <C-A-k> <PageUp>
inoremap <C-A-j> <ESC><C-E>i
inoremap <C-A-k> <ESC><C-Y>i
" Page up/down moving between tabs
nnoremap <C-h> :tabp<CR>
nnoremap <C-l> :tabn<CR>

" Sorry Vim guys, I'm used to readline
inoremap <C-a> <esc>I
inoremap <C-e> <esc>A
inoremap <C-d> <Delete>
inoremap <A-f> <C-Right>
inoremap <A-b> <C-Left>
"inoremap <A-d> <Esc><Right>dwi " Breaks small Ä

" More convenient moving between windows
nnoremap <M-h> <C-w>h
nnoremap <M-j> <C-w>j
nnoremap <M-k> <C-w>k
nnoremap <M-l> <C-w>l

" Open folds with space and create by Ctrl+space
map <Space> za
"nnoremap <C-Space> zfa}

" OmniComplete
"inoremap <C-Space> <C-x><C-u>
"inoremap <C-k> <C-x><C-o>

" QuickFix mappings
nnoremap <C-n> :cn<CR>
nnoremap <C-p> :cp<CR>

" FuzzyFindFile
nnoremap <C-f> :FufFile<CR>
inoremap <C-f> <Esc>:FufFile<CR>
nnoremap <C-b> :FufLine<CR>

" Tags completion
inoremap <C-]> <C-x><C-]>

"inoremap <C-b> <Esc>:FufBuffer<CR>

" Allow deleting selection without updating the clipboard (yank buffer)
noremap dd "_dd
vnoremap x "_x
vnoremap X "_X
" Don't move the cursor after pasting
" (by jumping to back start of previously changed text)
noremap p p`[
noremap P P`[

" Useless crap
noremap  <F1> :set invfullscreen<CR>
inoremap <F1> <ESC>:set invfullscreen<CR>a
" When scrolling, cursor stays in the middle
nnoremap <F1> :let &scrolloff=999-&scrolloff<CR>

" Visual text search
function! s:VSetSearch(cmdtype)
  let temp = @s
  norm! gv"sy
  let @/ = '\V' . substitute(escape(@s, a:cmdtype.'\'), '\n', '\\n', 'g')
  let @s = temp
endfunction
xnoremap * :<C-u>call <SID>VSetSearch('/')<CR>/<C-R>=@/<CR><CR>
xnoremap # :<C-u>call <SID>VSetSearch('?')<CR>?<C-R>=@/<CR><CR>

" Remove folds while in diff mode
if &diff
	set foldminlines=99999
endif

"#################################
"########### PLUGINS #############
"#################################
map <F3> :NERDTreeToggle<CR>

" Build tags of your own project with CTRL+F12
"map <C-F12> :!ctags -R --c++-kinds=+p --fields=+iaS --extra=+q .<CR>
noremap <F12> :!ectags -R --c++-kinds=+pl --fields=+iaS --extra=+q .<cr>
inoremap <F12> <Esc>:!ectags -R --c++-kinds=+pl --fields=+iaS --extra=+q .<cr>

" Paste Mode On/Off
map <F10> :call Paste_on_off()<CR>
set pastetoggle=<F10>
let paste_mode = 0 " 0 = normal, 1 = paste
func! Paste_on_off()
	if g:paste_mode == 0
		set paste
		set nonumber
		let g:paste_mode = 1
	else
		set number
		set nopaste
		let g:paste_mode = 0
		endif
	return
endfunc

" TagBar settings
nmap <F2> :TagbarToggle<cr>
let g:tagbar_autofocus=0
let g:tagbar_sort=1

" Session options
set sessionoptions=buffers,curdir,folds,tabpages
let sessionman_save_on_exit=0

" Ctags path(s)
set tags=./tags;/

" CScope thingies
if has("cscope")
	set csprg=/usr/local/bin/cscope
	set csto=0
	set cst
	set nocsverb
	" add any database in current directory
	if filereadable("cscope.out")
	    cs add cscope.out
	" else add database pointed to by environment
	elseif $CSCOPE_DB != ""
	    cs add $CSCOPE_DB
	endif
	set csverb
endif

