# $OpenBSD: dot.profile,v 1.4 2005/02/16 06:56:57 matthieu Exp $
#
# sh/ksh initialization

if [ -f ~/.profile ]; then
	. ~/.profile
fi

# Load env variables
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

